name: Build AERIS Dev Container Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true

permissions:
  packages: write

env:
  image_name: aeris-devcontainer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to registry
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
          cacheFrom: ghcr.io/${{ github.repository_owner }}/${{ env.image_name }}
          imageTag: ${{ inputs.tag }}
          push: always
          subFolder: src
